# Your full site URL. Example:
# "https://firozah.neocities.org/"
baseURL = "https://firozah-test-site.neocities.org/"
languageCode = "en-us"
# Title of your site
title = "hi!!!"
# How many feed entries to load at once
paginate = 6

[taxonomies]
tag = "tags"
author = "firozah"



[params]
skin = "macintosh"
author = "Firoooo"


#
# Totally optional cool stuff (see README for details)
#
# socialImage = "static/img/social.png" # site image for rich embeds
# customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
# webmentionUrl = "https://webmention.io/example/webmention"
# pingbackUrl = "https://webmention.io/example/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"

#
# For IndieAuth and the author card
#
# githubuser = "chihiro"
# twitteruser = "chihiro" # no @ in front
# mastodon = "https://mastodon.technology/@chihiro" # full link to your instance profile

[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"

[outputs]
# Output formats for your feed. You probably don't need to change this.
  home = ["HTML", "JSON", "RSS"]